version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .PWD }}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

    [[blocks.segments]]
    foreground = "p:os"
    style = "plain"
    template = " {{.Icon}} "
    type = "os"

    [[blocks.segments]]
    foreground = "p:os"
    style = "plain"
    template = "{{ if .Root }}\uF0E7{{ end }} "
    type = "session" 

    [[blocks.segments]]
    foreground = "p:pink"
    style = "plain"
    template = "{{ .Path }} "
    type = "path"

        [blocks.segments.properties]
        folder_icon = "..\uE5fe.."
        home_icon = "~"
        style = "agnoster_short"

    [[blocks.segments]]
    foreground = "p:lavender"
    style = "plain"
    template = "{{ .HEAD }} "
    type = "git"

        [blocks.segments.properties]
        branch_icon = "\uE725 "
        cherry_pick_icon = "\uE29b "
        commit_icon = "\uF417 "
        fetch_status = false
        fetch_upstream_icon = false
        fetch_bare_info = true
        merge_icon = "\uE727 "
        no_commits_icon = "\uF0c3 "
        rebase_icon = "\uE728 "
        revert_icon = "\uF0e2 "
        tag_icon = "\uF412 "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

    [[blocks.segments]]
    foreground = "p:closer"
    style = "plain"
    template = " ❱"
    type = "text"
    foreground_templates = [
        "{{if gt .Code 0}}p:red{{end}}",
        "{{if eq .Code 0}}p:closer{{end}}",
    ]

[transient_prompt]
background = "transparent"
template = " ❱ "
foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:closer{{end}}",
]

[secondary_prompt]
foreground = "p:closer"
background = "transparent"
template = " ❱❱ "

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"
red = "#F38BA8"
